### ISSUE TITLE
Unable to integrate the lib.so exported by L4Casadi and Acados into C

### ISSUE THREAD

**Issue by LilHu7** [Tim-Salzmann/l4casadi#10]
Hi, Tim

I constructed the OCP problem using L4casadi and acados in Python and generated libacados_ OCP_ Solver.so;

Aiming to develop this SQP_RTI solver in C environment, I developed my own main.cpp based on the template in interfaces/acados_template/acados_template/c_templates_tera/main.in.c .

Previously, all the required libs have been confirmed to be connected (Cmakelist compilation passed)
It reports "segmentation fault" when run the SQP solving code "status = {model_name}_acados_solve(acados_ocp_capsule);".

Can you provide some solutions of the above issue?

**Comment by Tim-Salzmann** [comment]
Hi,

Thanks for reaching out! Can you confirm this problem is related to L4CasADi vs just CasADi/Acados. E.g. when you try the same procedure with a pure CasADi model in acados **without** L4CasADi involved, you do not experience this issue?!

Best
Tim

**Comment by LilHu7** [comment]
hmm, 
That may be the problem of Acados sovler. Thanks!
