### ISSUE TITLE
The code portability issue for trained networks

### ISSUE THREAD

**Issue by LilHu7** [Tim-Salzmann/l4casadi#17]
Hi Tim,

When I try to porting my whole solvable project, l4casadi-acados solve frame, to another computer(computer1 - computer2), problems are encounted. The error reports are as follow:
terminate called after throwing an instance of 'c10::Error'
what(): open file failed because of errno 2 on fopen: . file path : /computer1/trained_net.pt (absolute path)
A stupid method is to create the same folder path of comput1 on the compute2 and copy *.pt to the folder, which result in poor portability.
How can we change call logic of *.pt from the absolute path to relative one?

Best 
Hu

**Comment by Tim-Salzmann** [comment]
Hi Hu,

please see the reply in this issue: https://github.com/Tim-Salzmann/l4casadi/issues/16

Best
Tim
