### ISSUE TITLE
l4casadi on Jetson Nano

### ISSUE THREAD

**Issue by baryn** [Tim-Salzmann/l4casadi#19]
Hi Tim,

Thank you for this great work, it helps a lot.
I wish to run l4casadi (with acados) on a Jetson Nano but as you probably know it does not support pytorch > 1.13 since Jetson Nano is limited to CUDA 10.2. Do you think one can "downgrade" l4casadi to pytorch 1.13 ? I naively replaced the following line to make it run with pytorch 1.13 to see if it would work directly:
`from torch.func import vmap, jacrev, hessian` replaced by `from functorch import vmap, jacrev, hessian` 
But I got a segmentation fault after running simple_nlp.py example (at line 26).

Does it makes sense to make it work with pytorch 1.13 and it is feasible ?

Thanks in advance,
Bryan

**Comment by Tim-Salzmann** [comment]
Hi Bryan,

Thanks for reaching out! I see that this is a problem. I would be open to seeing if it is feasible for  L4CasADi to be downwards compatible with PyTorch 1.13. 

You were correct that the first step is to replace `torch.func` with the former `functorch`.

Could you please post the entire error message you are getting with these changes?

Best
Tim

**Comment by Tim-Salzmann** [comment]
Hi Bryan,

I gave this a very quick try on my Mac. Using PyTorch 1.13 and replacing `torch.func` with `functorch`, I can run the `simple_mlp` example without problems. Wonder if this is a Jetson-specific problem?!

**Comment by baryn** [comment]
Cool. So, I currently work on the following image https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image
I created a conda environment with python 3.9 since the image has python 3.8.
I then simply commented the pytorch dependency in pyproject.toml
```
dependencies = [ 
   #"torch>=2.0", 
    "casadi>=3.6", 
    "jinja2>=3.1" 
]
```

It also implies changing `import torch.func as functorch` to `import functorch` in l4casadi/realtime/sensitivites.py

And built l4casadi with `CUDACXX=/usr/local/cuda/bin/nvcc pip install . --no-build-isolation`

However, I only get a minimal error message
```
$ python examples/simple_nlp.py 
Segmentation fault (core dumped)
```
Reading your previous message, I'll try something else. It might be a Jetson related issue indeed.

Cheers,
Bryan

**Comment by Tim-Salzmann** [comment]
It could be a Jetson GPU-related problem, too. I would suggest trying CPU-only installation of L4CasADi on the Jetson first to verify that this is working before switching to GPU.

Best
Tim

**Comment by baryn** [comment]
Yes, I have tried that. Digging deeper I see that I cannot get past line 124 of l4casadi.py.
It fails at this call 
```
self._cs_fun = cs.external(
            f'{self.name}',
            f"{self.build_dir / f'lib{self.name}'}{dynamic_lib_file_ending()}"
        )
```
It looks similar to this other issue related to casadi. https://github.com/casadi/casadi/issues/2616
After running the code sample I get the same segmentation fault too. I think I will take a moment to look around casadi then, maybe I will find a reason to this issue.

Cheers,
Bryan

**Comment by Tim-Salzmann** [comment]
Hi Bryan,

Any updates on this?

> To do so, I had to upgrade numpy, run pip install importlib-resources and replace the occurrences of importlib.resources with importlib_resources and torch.func by functorch for pytorch 1.13 (I saw that you made theses changes in the meantime :) ) But I believe I could make it work with python 3.9.

I made changes to make L4CasADi compatible with old `functorch` and `importlib_resources` out of the box.

>  I changed the compilation flag -std=c++17 to -std=c++14 , rebuilt it from source with gcc 10.5 and I was able to run the examples. 

This is a bit unclear to me. My understanding is that libtorch is compiled with c++17. 

Let me know if I can help

Best
Tim

**Comment by baryn** [comment]
Hi Tim,

Yes, sorry, I didn't make any progress on that. I am not sure what really prevents from installing in GPU mode. Probably a compatibility problem between CUDA 10.2 and gnu version. I will start by updating the repo with your changes and see what happens. I think I will close this issue and eventually raise a new one if the CPU mode is too limited for me.

Thanks again,
Bryan
