### ISSUE TITLE
experimental/propagate_const  is not available on Win

### ISSUE THREAD

**Issue by QSiY** [Tim-Salzmann/l4casadi#20]
Hi, I'm trying to use it on Windows10, is there a version for windows? Thanks

**Comment by Tim-Salzmann** [comment]
Hi,

Thanks for reaching out! Unfortunately, Windows is not officially supported. I do not have a Windows and thus do not have the means to test it.

Best
Tim

**Comment by Tim-Salzmann** [comment]
Windows is now supported with https://github.com/Tim-Salzmann/l4casadi/pull/60
