### ISSUE TITLE
Need an example of time series input

### ISSUE THREAD

**Issue by 438749902** [Tim-Salzmann/l4casadi#22]
Dear Tim Salzmann

Hello, your project has been of great help to me. I have successfully implemented an MPC controller based on the point2point deep learning model.

Due to the long and uncertain time delay of my controlled system. I need to use the deep learning prediction model of seq2point to identify. However, using l4casadi to achieve MPC control based on the seq2point model is very difficult for me. I couldn't find related example of it. Could you please add an example of using seq2point or seq2seq deep learning models to implement MPC?

Thank you again for your project's help to me,
Best wishes，
438749902

**Comment by Tim-Salzmann** [comment]
Hi,

Thanks for reaching out! I think this is not so much a problem of L4CasADi, as L4CasADi can embed time-series PyTorch models just as any other PyTorch model in a CasADi graph.

If I understand you correctly, you are mainly struggling to formulate the optimization problem around L4CasADi taking time-series data into account. If this is true it will be hard to provide you with an example as this is still an active research branch of how to best formulate such optimization problems.

Correct me if I am wrong here.

Best
Tim

**Comment by 438749902** [comment]
hi Tim，

Thank you for your answer,

I know your mean, l4casadi can convert time series model to casadi model. But use casadi and acados to write a MPC is an another hard problem which need me to resolve. I will read docs and search project about this.

Thank you, you can close the issue.
Best wishes
