### ISSUE TITLE
real time L4casadi c++

### ISSUE THREAD

**Issue by vonkin** [Tim-Salzmann/l4casadi#27]
Hi Tim,

When will the C++ version of real time L4casadi be online? I am currently troubled by the python gc mechanism and want to completely rewrite it in c++.

thanks

**Comment by Tim-Salzmann** [comment]
Hi,

I currently do not have plans to work on a pure C++ version of RT-L4CasADi. I would, however, be happy to review and accept a pull request for this if you manage to get this working.

Best
Tim
