### ISSUE TITLE
Is RealTimeL4CasADi suitble for RNN?

### ISSUE THREAD

**Issue by vonkin** [Tim-Salzmann/l4casadi#29]
I want to know if l4c.RealTimeL4CasADi suitable for RNN, for example LSTM, GRU

**Comment by Tim-Salzmann** [comment]
Hi,

RealTimeL4CasADi generally works with RNNs. The specific use (e.g. when to update approximations and which inputs to fix as constant/variable for the approximation) is dependent on your use-case.

Best
Tim

**Comment by vonkin** [comment]
Thank you very much. I appreciate your work very much and hope you can achieve greater breakthroughs in this area

**Comment by Tim-Salzmann** [comment]
You are welcome! Feel free to close this issue if it is resolved.

Thanks
Tim
