### ISSUE TITLE
support for python 3.8

### ISSUE THREAD

**Issue by mandralis** [Tim-Salzmann/l4casadi#31]
I need to run l4casadi in python 3.8 since it makes it easier to use with ROS2 foxy. Is it possible to make it backwards compatible with Python 3.8 ? 

Thanks !

**Comment by Tim-Salzmann** [comment]
Hi Ioannis,

Thanks for reaching out. Did you check that it is indeed not compatible with 3.8 as of now?

I would think that if it is not compatible it should only be a couple of lines to change.

Let me know

Best
Tim

**Comment by Tim-Salzmann** [comment]
I just gave it a try, and it seems to work for Python 3.8.

**Comment by mandralis** [comment]
It worked when building from source. For some reason I have to run the
following to get it to work:
export TORCH_CUDA_ARCH_LIST="8.0 8.6 8.9 9.0"
