### ISSUE TITLE
Using realtime l4casadi with acados

### ISSUE THREAD

**Issue by mandralis** [Tim-Salzmann/l4casadi#33]
Hello Tim, 

I am trying to use a neural network model in a real-time mpc framework that is running with acados. What is the recommended way of doing this. A bit of context:

Even when I am using a simple MLP that is wrapped with l4casadi and compiled with acados, the computation time of each MPC step becomes prohibitively expensive to run in real time. 

To circumvent this I am trying to use the RealTimeL4Casadi class. However, I am unsure on how to get it to work with acados. Do you have a simple use case or example that can help me get started ? 

Best,
Ioannis

**Comment by Tim-Salzmann** [comment]
Hi Ioannis,

yes, there is an exampe in the examples / realtime folder:

https://github.com/Tim-Salzmann/l4casadi/blob/main/examples/realtime/mpc_mlp_example.py

Best
Tim

**Comment by mandralis** [comment]
Thanks. This clarified things
