### ISSUE TITLE
fatal error: filesystem: No such file or directory

### ISSUE THREAD

**Issue by Ozzey** [Tim-Salzmann/l4casadi#35]
Hello! Amazing work with l4casadi!

While installing it in my ubuntu system I faced the following error:

`fatal error: filesystem: No such file or directory
       #include <filesystem>
                ^~~~~~~~~~~~
      compilation terminated.
      ninja: build stopped: subcommand failed.
`

I managed to fix the issue by updating gcc and g++ to 11.0 (I think >=9.0 should work fine)

I think it's worth mentioning in the installation guide that you need this version of gcc and g++ to build l4casadi. 
Also I have tried building a docker file for l4casadi (and acados) so maybe you'd be interested in adding the docker support officially?

**Comment by Tim-Salzmann** [comment]
Hi Aditya,

Thanks for bringing this to my attention. I added a quick note in the README about minimal requirements for GCC.

Please share your docker file here so, at the very least, other people can find it. I will then think if and how we can include it in the repo.

Thanks
Tim

**Comment by Ozzey** [comment]
Here is the [docker file](https://pastebin.com/0E7Ln2M3). It's based on the official cuda dockerfile by Nvidia and uses ubuntu22.04 as base and then installs the required cuda libraries and the supported torch version. It also has installation option for acados but you can remove it if necessary.

**Comment by Tim-Salzmann** [comment]
Thanks!
