### ISSUE TITLE
Issue with SX symbolic variables

### ISSUE THREAD

**Issue by AFusco99** [Tim-Salzmann/l4casadi#36]
Hello,
I tried executing the acados example, the only change I made was substituting the MX symbolic variables to SX symbolic variables, as I needed make to them compatible with another library. However this change always returns this error : 

`RuntimeError: Error in Function::call for 'learned_dyn' [External] at .../casadi/core/function.cpp:370: .../casadi/core/function_internal.cpp:2013: 'eval_sx' not defined for External`

Could you tell if there are additional change to be made in order to use SX variables or if they are not supported by this library.
I am using the latest version of casadi 3.6.5 and the latest of l4casadi and python3.10
Thank you very much

**Comment by Tim-Salzmann** [comment]
Hi,

Thanks for reaching out. CasADI only supports MX variables for external functions (which L4CasADi effectively is). As such there is nothing I can do to support this from the L4CasADi side.

Best
Tim
