### ISSUE TITLE
FileNotFoundError: Could not find module '...\site-packages\l4casadi\lib\libl4casadi.dll' (or one of its dependencies)

### ISSUE THREAD

**Issue by fengqics** [Tim-Salzmann/l4casadi#38]
```
Traceback (most recent call last):
  File "D:\Onedrive\Python\rlmpc\l4_test.py", line 3, in <module>
    import l4casadi
  File "C:\Users\Tomato\AppData\Local\Programs\Python\Python39\lib\site-packages\l4casadi\__init__.py", line 15, in <module>
    ctypes.CDLL(str(lib_path), mode=ctypes.RTLD_GLOBAL)
  File "C:\Users\Tomato\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Tomato\AppData\Local\Programs\Python\Python39\lib\site-packages\l4casadi\lib\libl4casadi.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
After installing the cpu version of torch(2.3.1+cpu), Python version is 3.9. I executed the pip command to install l4casadi. The installation was successful, but the import in the code reported an error, indicating that there was no dll file. I checked in the local resource manager and found that there was indeed no dll file. How can I solve this problem?

**Comment by Tim-Salzmann** [comment]
Hi,

Unfortunately, Windows is not supported at this point.

Sorry
Tim

**Comment by fengqics** [comment]
Ok thanks for the reply, that's the reason.

**Comment by Tim-Salzmann** [comment]
Windows is now supported with https://github.com/Tim-Salzmann/l4casadi/pull/60
