### ISSUE TITLE
Problems with running acados.py

### ISSUE THREAD

**Issue by Ucccccc** [Tim-Salzmann/l4casadi#40]
Hello, may I ask if you have ever encountered this problem? I successfully built the python interface of acados on windows, then, I tried using realtime and Naive and both worked fine. I ran mpc_mlp_example.py and got the normal result as shown in Figure 1. However, when I ran acados.py, it prompted me that the L4CasADi link failed as shown in Figure 2.
![image](https://github.com/Tim-Salzmann/l4casadi/assets/89255910/06f008f4-3b31-4ccb-b21a-df34e5ddd52a)

![image](https://github.com/Tim-Salzmann/l4casadi/assets/89255910/4cea2639-b104-4724-a701-e32188060e52)

**Comment by Tim-Salzmann** [comment]
This seems to be Windows? "collect2.exe"


Windows is not officially supported.

**Comment by Ucccccc** [comment]
Yes I am using windows build, does l4casadi not support windows currently?

**Comment by Tim-Salzmann** [comment]
Unfortunately, it does not. I am surprised that Naive and Realtime do work, but this is good to know.

Also see: https://github.com/Tim-Salzmann/l4casadi/issues/24

**Comment by Ucccccc** [comment]
OK, thanks, but it seems that realtime is not much different from this, there are two more paths

**Comment by Tim-Salzmann** [comment]
If this answers your questions, feel free to close the issue.

Thanks
Tim

**Comment by Ucccccc** [comment]
Does Real-time L4CasADi only support MLP? Does it support CNN model?

**Comment by Tim-Salzmann** [comment]
Real-time L4CasADi supports any PyTorch model. Naive L4CasADi only supports MLPs.

**Comment by Ucccccc** [comment]
THANKS!!!

**Comment by Tim-Salzmann** [comment]
Windows is now supported with https://github.com/Tim-Salzmann/l4casadi/pull/60
