### ISSUE TITLE
No Performance Improvement with ·scripting=False·

### ISSUE THREAD

**Issue by xueminchi** [Tim-Salzmann/l4casadi#43]
Hi @Tim-Salzmann 

I have tested the batch version of l4casadi in an MPC demo, and it improves computational efficiency a lot, especially as the number of evaluations of the l4casadi model increases.

However, I am puzzled because the computational time of my code does not change when I enable or disable the new function (`scripting=False` or `scripting=True`), as introduced. This behavior is consistent with the script nerf_trajectory_optimization_batched.py, where `scripting=False` does not seem to affect the speed in the executing stage.

Best,
Xuemin

**Comment by Tim-Salzmann** [comment]
Hi,

This is somewhat expected. JIT scripting and torch compile target roughly the same use-case (efficient inference). Torch compile is the newer approach and will be further developed in the future. JIT scripting will not be further developed in the future.

On my machine compiling is marginally faster in execution time (much slower in problem setup) (50ms faster) on the NeRF example.

Let me know if this answers your question.

**Comment by Tim-Salzmann** [comment]
Hi,

v2 is still in development. Setting `scripting=False` will have no influence in the current version. Compile is not stable enough yet from the torch side.

Best
Tim

**Comment by xueminchi** [comment]
> Hi,
> 
> v2 is still in development. Setting `scripting=False` will have no influence in the current version. Compile is not stable enough yet from the torch side.
> 
> Best Tim

Thanks!
