### ISSUE TITLE
Using a neural network as the terminal cost with l4casadi + acados

### ISSUE THREAD

**Issue by mrunaljsarvaiya** [Tim-Salzmann/l4casadi#51]
Hey,

Not an issue but a question. I'm hoping to get confirmation that it is possible to use a neural network as the terminal cost for an MPC built through l4casadi + acados. This would be similar to what's been done in the AC4MPC paper, however I couldn't locate their code. 

I'd like to do something similar to `ocp.model.cost_expr_ext_cost_e = l4c_y_expr`. 

Thanks in advance!

**Comment by Tim-Salzmann** [comment]
Hi,

Thanks for reaching out! Could you clarify what your problem is? Is the code giving you an error / are the results not what you expect?

Best
Tim

**Comment by mrunaljsarvaiya** [comment]
Hey Tim, 

The solver was throwing an error but I wasn't sure if it was because of the additional pytorch model or other parts of my implementation. Turns out it was a bug on my end. Thanks though!
