### ISSUE TITLE
issue about batched pytorch models 

### ISSUE THREAD

**Issue by alwaysbyx** [Tim-Salzmann/l4casadi#53]
I try to run example code

```
pyTorch_model = MultiLayerPerceptron()
l4c_model = l4c.L4CasADi(pyTorch_model, device='cpu')  # device='cuda' for GPU

x_sym = cs.MX.sym('x', 1, 2)
y_sym = l4c_model(x_sym)
```

However it raise the error: ValueError: For batched PyTorch models only vector inputs are allowed.

**Comment by Tim-Salzmann** [comment]
Hi,

could you make sure you are on the latest version of L4CasADi? E.g. L4CasADi 2.0.

Either by cloning the git directly or v2 should be available via pip soon.

Thanks
Tim
