### ISSUE TITLE
cannot find libl4casadi.dll

### ISSUE THREAD

**Issue by desert1024** [Tim-Salzmann/l4casadi#57]
Hello, I installed it according to your steps and found problems when running the code.
The problem description is: unable to find \L4casadi\lib\libl4casadi.dll

**Comment by Tim-Salzmann** [comment]
Hi, unfortunately, this library is neither tested nor officially supported on Windows.

Best
Tim

**Comment by desert1024** [comment]
已收到，谢谢

**Comment by desert1024** [comment]
Thanks.



---Original---
From: "Tim ***@***.***&gt;
Date: Tue, Nov 26, 2024 02:16 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Tim-Salzmann/l4casadi] cannot find libl4casadi.dll (Issue #57)




 
Hi, unfortunately, this library is neither tested nor officially supported on Windows.
 
Best
 Tim

**Comment by Tim-Salzmann** [comment]
Windows is now supported with https://github.com/Tim-Salzmann/l4casadi/pull/60

**Comment by desert1024** [comment]
已收到，谢谢
