### ISSUE TITLE
OSError：undefined symbol

### ISSUE THREAD

**Issue by wensijie** [Tim-Salzmann/l4casadi#8]
Dear colleagues：
I have some questions about the L4c installation.

**Environment：**
WSL2 - Ubuntu 20.04
python 3.10  in Anconda
CUDA 12.2
PyTorch==2.0.0

**Problem:**
I installed the L4c  according to the requirement of  [Installation](https://github.com/Tim-Salzmann/l4casadi)
But when I run  `example/readme.py` the outputs is 

`
Exception has occurred: OSError
/home/wen/anaconda3/envs/Pytorch/lib/python3.10/site-packages/l4casadi/lib/libl4casadi.so: undefined symbol: _ZN5torch3jit22optimize_for_inferenceERNS0_6ModuleERKSt6vectorISsSaISsEE
  File "/home/wen/ToolBox/L4CasADi/l4casadi/examples/simple_nlp.py", line 2, in <module>
    import l4casadi as l4c
OSError: /home/wen/anaconda3/envs/Pytorch/lib/python3.10/site-packages/l4casadi/lib/libl4casadi.so: undefined symbol: _ZN5torch3jit22optimize_for_inferenceERNS0_6ModuleERKSt6vectorISsSaISsEE
`

Could you tell me how to solve this problem? thank you

**Comment by Tim-Salzmann** [comment]
Hi,

thanks for reaching out! This is the first time I have come across this problem. It could be a problem with a mismatch in PyTorch version. I assume you have PyTorch with GPU support installed?! Did you install L4Casadi with `USE_CUDA=TRUE CUDACXX=<PATH_TO_nvcc> pip install .`?

**Comment by wensijie** [comment]
Thanks  for your reply.  I have solved the problem.  I found that this error code also appears when installing` pytorch_geometric`. So I reinstalled the Pytorch as the following [https://github.com/pyg-team/pytorch_geometric/issues/1080](url) , and the problem was resolved.
